builds:
- id: spin-plugin-k8s
  main: ./
  binary: k8s
  env:
  - CGO_ENABLED=0
  ldflags:
  - "-s -w -X github.com/spinkube/spin-plugin-k8s/pkg/cmd.Version={{.Version}}"
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  - arm64

snapshot:
  name_template: "canary"

archives:
- builds:
  - spin-plugin-k8s
  name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  wrap_in_directory: false
  format: tar.gz
  files:
  - LICENSE
