builds:
- id: spin-plugin-kube
  main: ./
  binary: kube
  env:
  - CGO_ENABLED=0
  ldflags:
  - "-s -w -X github.com/spinkube/spin-plugin-kube/pkg/cmd.Version={{.Version}}"
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  - arm64

archives:
- builds:
  - spin-plugin-kube
  name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  wrap_in_directory: false
  format: tar.gz
  files:
  - LICENSE
