name = "kube"
description = "Commands for publishing applications to Kubernetes using the spin-operator."
version = "0.1.0"
spin_compatibility = ">=2.0"
license = "Apache-2.0"
homepage = "https://github.com/spinkube/spin-plugin-kube"
package = "./bin/spin-kube"
