  
{{- if .Values.runtimeConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-runtime-config
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  runtime-config.toml: {{ .Values.runtimeConfig }}
{{- end }}