name: Release

on:
  push:
    tags:
      - "*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.22.x"

    - name: Install dependencies
      run: go mod download

    - name: GoReleaser
      uses: goreleaser/goreleaser-action@v5.0.0
      with:
        version: latest
        args: release --clean ${{ github.ref == 'refs/heads/main' && '--snapshot' || '' }}
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Release Plugin
      uses: rajatjindal/spin-plugin-releaser@v1
      with:
        github_token: ${{ github.token }}
        upload_checksums: true
        template_file: contrib/spin-plugin.json.tmpl
