name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GOPRIVATE: "github.com/spinkube/spin-operator"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.21"

    - name: Setup Private Git Repo Access
      run: |
        echo "machine github.com login fermybot password ${GH_ACCESS_TOKEN}" > $HOME/.netrc
      env:
        GH_ACCESS_TOKEN: ${{ secrets.ACTIONS_PRIVATE_REPO_CHECKOUT_TOKEN }}

    - name: Build
      run: go build -o spin-plugin-k8s main.go

    - name: Run tests
      run: go test ./...
